### PR TITLE
Update functions.r

### PR DESCRIPTION
**Pull request by ludgergoeminne**
Otherwise I get the error "Result must have length x, not 3x" if I try with a data frame with x rows.

### CODE REVIEW

**Comment by adder** [comment]
Hi 

I don't get it. What are you summing? There should be only 1 df value per row/protein.

Can you provide a reproducible example of this error. (Just can use (synthetic) data of few proteins)
Preferable use reprex (https://reprex.tidyverse.org/index.html) for this example if you post it here.

Thanks

**Comment by ludgergoeminne** [comment]
Download: 
test

Change extension ".gif" to ".RData" because not supported by GitHub.
Then run this:

suppressWarnings(msqrobsum(data = test, formulas = expression ~ (1|cond_exp), group_vars = 'protein'))

Gives error: "Error: Result must have length 10, not 30"

**Comment by adder** [comment]
Hi
Sorry, I.m not able to open that file. I tried to download it and rename it but R doesn't want to load it.

I still prefer a minimal reproducable example though. With the minimal number of proteins and samples that produces that error. You can just use some random numbers as intensities.
Msqrobsum also reads data.frames so you do not really have to create an MSnBase set :) That's probably easier.

Also if you use reprex to post the R code here, then I also now exactly what's in your R session. e.g. which packages and their version

thanks

**Comment by ludgergoeminne** [comment]
Strange, it works with me if I rename it to "test.RData".
It's already a tibble, so it should be easy to import.

**Comment by adder** [comment]
The dataset only contains 1 sample and 1 condition so you can not fit an model on this data. 
IF you summarise only, you also see that it only gives 1 value per protein.

The error was indeed a bit unclear but warranted :)

**Comment by ludgergoeminne** [comment]
Ah yes indeed, embarassing :p

**Pull request closed without merging**
